---
name: Image-ANSI
version: 0.08
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: 'Load, create, manipulate and save ANSI files'
license: perl
requires:
  Class::Accessor: 0
  File::SAUCE: 0
  GD: 0
provides:
  Image::ANSI:
    file: lib/Image/ANSI.pm
    version: 0.08
  Image::ANSI::Font:
    file: lib/Image/ANSI/Font.pm
    version: 0.03
  Image::ANSI::Font::8x16:
    file: lib/Image/ANSI/Font/8x16.pm
    version: 0.01
  Image::ANSI::Font::8x8:
    file: lib/Image/ANSI/Font/8x8.pm
    version: 0.01
  Image::ANSI::Palette:
    file: lib/Image/ANSI/Palette.pm
    version: 0.03
  Image::ANSI::Palette::VGA:
    file: lib/Image/ANSI/Palette/VGA.pm
    version: 0.01
  Image::ANSI::Parser:
    file: lib/Image/ANSI/Parser.pm
    version: 0.05
  Image::ANSI::Pixel:
    file: lib/Image/ANSI/Pixel.pm
    version: 0.03
  Image::ANSIMation:
    file: lib/Image/ANSIMation.pm
    version: 0.02
  Image::ANSIMation::Parser:
    file: lib/Image/ANSIMation/Parser.pm
    version: 0.02
generated_by: Module::Build version 0.2611
